language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql -e 'create database IF NOT EXISTS myguestbook'
  - mysql myguestbook < src/myguestbook.sql
  - composer install --prefer-source --dev

script:
  - phpcs .
  - phpunit .

notifications:
  email: false
