language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database IF NOT EXISTS myguestbook'
  - mysql myguestbook < myguestbook.sql

script:
  - ./vendor/bin/phpcs lib --standard=PSR2
  - ./vendor/bin/phpunit

notifications:
  email: false
